### ISSUE TITLE
Initial tracking

### ISSUE THREAD

**Issue by samueldurantes** [samueldurantes/simpy#2]
## Goal

The main goal of the project is to build an API that returns a mortgage simulation, where the client makes a request to the `/simulations` endpoint, specifying the bank, the financing value, the number of installments, and their age.

With this information, the following response should be returned:

```json
{
  "bank": "string",
  "financing_value": "string",
  "age": "number",
  "installments": [
    {
      "installment": "number",
      "value": "float"
    }
  ]
}
```

### General

- [x] Set up the initial Flask application
- [x] Create an endpoint `/simulations` that receives the necessary data for the simulation as query parameters
- [x] Add validations for all the fields provided by the client
- [x] Ensure that only one error is returned at a time, instead of returning all at once
- [x] Add tests using `unittest`
- [x] ~~Create a documentation using Swagger or OpenAPI~~

### Business Rules

- [x] Create an interface that will call the function of the bank specified by the client to calculate the mortgage
- [x] Implement the simulator for Itaú
- [x] Implement the simulator for Bradesco
- [x] Implement the simulator for Caixa
- [x] Implement the simulator for Inter
- [x] Implement the simulator for Santander
